Repository pagopa/pagopa-qi-fdr-kpi-service, pull requests merged in 2024-12, with the labels that each got.

#1 [PPABV-83] feat: add project setup with spring initializr
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/check-pr-semver-labels/action.yml
  .github/workflows/check_pr.yml
  .github/workflows/deploy.yml
  .gitignore
  .java-version
  .pre-commit-config.yaml
  CODEOWNERS
  build.gradle.kts
  eclipse-style.xml
  gradle.lockfile
  gradle.propetries
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/kotlin/it/pagopa/qi/fdrkpiservice/PagopaQiFdrKpiServiceApplication.kt
  src/main/resources/application.properties
  src/main/resources/banner.txt
  src/main/resources/logback-spring.xml
  src/test/kotlin/it/pagopa/qi/fdrkpiservice/PagopaQiFdrKpiServiceApplicationTests.kt
Labels: skip-release

#4 [PPABV-84] Configure local run
  Dockerfile
  docker-compose.yml
  docker-local/azure-data-explorer/Dockerfile
  docker-local/azure-data-explorer/kusto-init.sh
  docker-local/azure-data-explorer/start-kusto.sh
  docker-local/qi-fdr-kpi/qi-fdr-kpi.env
Labels: skip-release, size/small

#2 [PPABV-87] feat: add openapi specs
  api-spec/v1/openapi.yaml
Labels: skip-release, ignore-for-release

#5 [PPABV-86] Add code review pipeline
  .devops/code-review-pipelines.yml
  README.md
Labels: skip-release, size/small

#6 [PPABV-85] feat: pipelines deploy and helm DEV
  .devops/azure-templates/api-tests.yml
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/gradle-github-release.yml
  .devops/azure-templates/helm-microservice-chart-deploy.yml
  .devops/deploy-pipelines.yml
  .gitignore
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
Labels: skip-release, size/large

#3 [PPABV-92] feat: add openapi generator
  api-spec/v1/openapi.yaml
  build.gradle.kts
  gradle.lockfile
  src/main/kotlin/it/pagopa/qi/fdrkpi/PagopaQiFdrKpiServiceApplication.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/controller/v1/FdrKpiController.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/PagopaQiFdrKpiServiceApplicationTests.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/controller/v1/FdrKpiControllerTest.kt
Labels: skip-release, ignore-for-release, size/small

#10 [PPABV-99] feat: change spring webflux approach
  build.gradle.kts
  gradle.lockfile
  gradle/verification-metadata.xml
  src/main/kotlin/it/pagopa/qi/fdrkpi/controller/v1/FdrKpiController.kt
  src/main/resources/banner.txt
  src/test/kotlin/it/pagopa/qi/fdrkpi/controller/v1/FdrKpiControllerTest.kt
Labels: minor, chart-minor, size/small

#11 fix(build): Add api-spec in openapi
  Dockerfile
Labels: size/small

#13 [PPABV-102] feat: update openapi
  api-spec/v1/openapi.yaml
  src/main/kotlin/it/pagopa/qi/fdrkpi/controller/v1/FdrKpiController.kt
Labels: skip-release, ignore-for-release

#15 [PPABV-93] chore: update README.md
  README.md
Labels: skip-release, ignore-for-release

#14 [PPABV-101] feat: add FDR KPI response builder
  src/main/kotlin/it/pagopa/qi/fdrkpi/utils/FdrKpiResponseBuilder.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/utils/ResponseBuilderTest.kt
Labels: minor, chart-minor, size/small

#12 [PPABV-94] feat: kusto client configuration
  .env.local
  build.gradle.kts
  gradle.lockfile
  gradle/verification-metadata.xml
  src/main/kotlin/it/pagopa/qi/fdrkpi/configurations/KustoConfig.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/configurations/KustoConfigTest.kt
  src/test/resources/application-test.properties
Labels: minor, chart-minor, size/small

#17 chore: update dataexplorer config
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#16 [PPABV-96] feat: add FdrKpiService
  .env.local
  docker-local/azure-data-explorer/kusto-init.sh
  gradle/verification-metadata.xml
  src/main/kotlin/it/pagopa/qi/fdrkpi/controller/v1/FdrKpiController.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/service/FdrKpiService.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/utils/FdrKpiPeriod.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/utils/QueryUtils.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/controller/v1/FdrKpiControllerTest.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/service/FdrKpiServiceTest.kt
Labels: minor, chart-minor, size/small

#20 chore: update openapi
  api-spec/v1/openapi.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/qi/fdrkpi/controller/v1/FdrKpiController.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/service/FdrKpiService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/qi/fdrkpi/controller/v1/FdrKpiControllerTest.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/service/FdrKpiServiceTest.kt
Labels: minor, chart-minor, size/small

#21 [PPABV-105] Add broker psp query
  docker-local/azure-data-explorer/kusto-init.sh
  src/main/kotlin/it/pagopa/qi/fdrkpi/dataprovider/kusto/v1/KustoQueries.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/service/FdrKpiService.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/utils/QueryUtils.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/dataprovider/kusto/v1/KustoQueriesTest.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/service/FdrKpiServiceTest.kt
Labels: minor, chart-minor, size/small

#23 chore: increase resource for uat and prod
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#24 fix(pipeline): fix tagSource as gitTag
  .devops/azure-templates/gradle-github-release.yml
Labels: size/small, patch, chart-patch

#25 chore: add elk secret
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#18 [PPABV-97] feat: add info and debug logs
  docker-local/qi-fdr-kpi/qi-fdr-kpi.env
  src/main/kotlin/it/pagopa/qi/fdrkpi/configurations/KustoConfig.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/controller/v1/FdrKpiController.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/dataprovider/kusto/v1/KustoQueries.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/exceptionhandler/ApiError.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/exceptionhandler/ExceptionsHandler.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/exceptionhandler/RestApiException.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/service/FdrKpiService.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/utils/FdrKpiResponseBuilder.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/utils/QueryUtils.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/controller/v1/FdrKpiControllerTest.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/exceptionhandler/ApiErrorTest.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/exceptionhandler/ExceptionHandlerTest.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/exceptionhandler/RestApiExceptionTest.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/service/FdrKpiServiceTest.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/utils/QueryUtilsTest.kt
Labels: skip-release, ignore-for-release, size/large

#26 fix: force recreate secret
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#22 [PPABV-104] feat: Implemented Exception Handler
  .env.local
  docker-local/qi-fdr-kpi/qi-fdr-kpi.env
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/qi/fdrkpi/service/FdrKpiService.kt
  src/main/kotlin/it/pagopa/qi/fdrkpi/utils/QueryUtils.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/qi/fdrkpi/service/FdrKpiServiceTest.kt
  src/test/kotlin/it/pagopa/qi/fdrkpi/utils/QueryUtilsTest.kt
  src/test/resources/application-test.properties
Labels: minor, chart-minor, size/small

#27 chore: config deployment
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, major, chart-major

#28 fix: prod config
  helm/values-prod.yaml
Labels: size/small, patch, chart-patch
